#!/user/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Nonetallt\Jinitialize\JinitializeApplication;

$app = new JinitializeApplication(__DIR__);
$app->registerPlugins(__DIR__.'/boostrap/cache/plugins.php');
$app->run();

/* var_dump($app->getPlugins()); */
